name: fl_nodes
description: A lightweight, scalable, and highly customizable package that empowers Flutter developers to create dynamic, interactive, and visually appealing node-based UIs.
version: 0.1.0+1

homepage: https://williamkaroldicioccio.github.io/fl_nodes/
repository: https://github.com/WilliamKarolDiCioccio/fl_nodes
issue_tracker: https://github.com/WilliamKarolDiCioccio/fl_nodes/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - visual-scripting
  - workflow-editor
  - node-editor

funding:
  - https://studio.buymeacoffee.com/dashboard

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_context_menu: ^0.2.0
  keymap: ^0.0.92
  os_detect: ^2.0.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"
